"""esquema multiempresa inicial

Revision ID: ade15461db9e
Revises:
Create Date: 2026-06-19 04:54:41.624144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
import uuid
import datetime

# revision identifiers, used by Alembic.
revision: str = 'ade15461db9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ID fijo de la empresa default -- coincide con DEFAULT_EMPRESA_ID en database.py
DEFAULT_EMPRESA_ID = "00000000-0000-0000-0000-000000000001"


def upgrade() -> None:
    """Upgrade schema."""
    # Esta es una migracion limpia desde cero. Las tablas de la v1
    # (analisis, hashes_documentos sin empresa_id) solo contenian datos
    # de prueba -- se confirmo explicitamente que pueden eliminarse sin
    # perdida real. IF EXISTS para que esto sea seguro de correr incluso
    # si la DB ya estaba vacia o nunca tuvo esas tablas.
    op.execute(sa.text("DROP TABLE IF EXISTS analisis CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS hashes_documentos CASCADE"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('limite_mensual', sa.Integer(), nullable=True),
    sa.Column('analisis_consumidos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Empresa default -- mientras no exista multiempresa real con
    # autenticacion, todo el sistema usa este ID fijo (ver
    # database.DEFAULT_EMPRESA_ID). Se inserta aqui para que las FK de
    # analisis/hashes_documentos/usuarios siempre tengan un registro
    # valido al que apuntar desde el primer momento.
    op.execute(
        sa.text(
            "INSERT INTO empresas (id, nombre, plan, status, analisis_consumidos, created_at, updated_at) "
            "VALUES (:id, :nombre, :plan, :status, 0, :ahora, :ahora)"
        ).bindparams(
            id=uuid.UUID(DEFAULT_EMPRESA_ID),
            nombre="Empresa Default",
            plan="free",
            status="active",
            ahora=datetime.datetime.utcnow(),
        )
    )

    op.create_table('analisis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('score_claude', sa.Numeric(), nullable=True),
    sa.Column('score_iat', sa.Numeric(), nullable=True),
    sa.Column('score_final', sa.Numeric(), nullable=True),
    sa.Column('riesgo', sa.String(length=32), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=255), nullable=True),
    sa.Column('archivo_tipo', sa.String(length=50), nullable=True),
    sa.Column('monto_detectado', sa.Numeric(), nullable=True),
    sa.Column('banco_detectado', sa.String(length=100), nullable=True),
    sa.Column('clabe_detectada', sa.String(length=18), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_banco_detectado'), 'analisis', ['banco_detectado'], unique=False)
    op.create_index(op.f('ix_analisis_empresa_id'), 'analisis', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_analisis_fecha'), 'analisis', ['fecha'], unique=False)
    op.create_index(op.f('ix_analisis_hash_sha256'), 'analisis', ['hash_sha256'], unique=False)
    op.create_index(op.f('ix_analisis_monto_detectado'), 'analisis', ['monto_detectado'], unique=False)
    op.create_index(op.f('ix_analisis_riesgo'), 'analisis', ['riesgo'], unique=False)
    op.create_table('hashes_documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('primer_analisis', sa.DateTime(), nullable=False),
    sa.Column('ultimo_analisis', sa.DateTime(), nullable=False),
    sa.Column('veces_visto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'hash_sha256', name='uq_hash_por_empresa')
    )
    op.create_index(op.f('ix_hashes_documentos_hash_sha256'), 'hashes_documentos', ['hash_sha256'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_hashes_documentos_hash_sha256'), table_name='hashes_documentos')
    op.drop_table('hashes_documentos')
    op.drop_index(op.f('ix_analisis_riesgo'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_monto_detectado'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_hash_sha256'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_fecha'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_empresa_id'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_banco_detectado'), table_name='analisis')
    op.drop_table('analisis')
    op.drop_table('empresas')
    # ### end Alembic commands ###