"""crear tablas hashes_documentos y analisis

Revision ID: d313b95d53e7
Revises: 
Create Date: 2026-06-17 07:19:06.793811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd313b95d53e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('score_claude', sa.Numeric(), nullable=True),
    sa.Column('score_iat', sa.Numeric(), nullable=True),
    sa.Column('score_final', sa.Numeric(), nullable=True),
    sa.Column('riesgo', sa.String(length=32), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_hash_sha256'), 'analisis', ['hash_sha256'], unique=False)
    op.create_table('hashes_documentos',
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('primer_analisis', sa.DateTime(), nullable=False),
    sa.Column('ultimo_analisis', sa.DateTime(), nullable=False),
    sa.Column('veces_visto', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hash_sha256')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashes_documentos')
    op.drop_index(op.f('ix_analisis_hash_sha256'), table_name='analisis')
    op.drop_table('analisis')
    # ### end Alembic commands ###